# Generated by Django 3.2.8 on 2022-09-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(default='https://', verbose_name='Ссылка'),
        ),
    ]
