# Generated by Django 3.2.8 on 2022-10-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_project', '0002_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='update_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
