# Generated by Django 4.1.1 on 2022-11-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_project', '0002_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
